### PR TITLE
Autointerp eval

### PR DESCRIPTION
**Pull request by callummcdougall**
This is the mostly-complete autointerp eval setup. A few notes:

- Within `evals/autointerp` you can run `python demo.py --api_key "YOUR_API_KEY" to see it in action, or you can read `logs_4.txt` or `logs_100.txt` to see the output that was produced from running this
- The file `evals/autointerp/README.md` contains a short explanation of how it works, as well as the filestructure
- Roughly speaking I've stuck to the EleutherAI way of implementing autointerp, with some minimal changes here and there
- I've created a few utils functions for indexing with a buffer, and put them in a new file `indexing_utils.py`
- There's also a file `sae_encode.py` which gives methods for computing only a subset of latents (this will be useful until the PR gets merged in SAELens)

### CODE REVIEW

**Comment by adamkarvonen** [comment]
A few notes from testing this out:

I had to load SAE Bench Gemma SAEs like this, otherwise one part of the SAE (maybe the bias term?) was on cpu.

```
sae = SAE.from_pretrained(release, sae_id, device=str(device))[0]
sae = sae.to(device=device)
```

It looks like this eval is being ran on 156k tokens, not 10M. I believe it is because self.batch_size is set like this:

self.batch_size = cfg.total_tokens // model.cfg.n_ctx

For gemma, n_ctx is 8192. However, the activation store context size == sae.cfg.context_size, which is 128 for SAE bench SAEs and 1024 for GemmaScope. So, we end up using less tokens. If I print tokens.shape [here](https://github.com/callummcdougall/SAE_Bench_Template/blob/callum/autointerp/evals/autointerp/main.py#L317), I get (1220, 128), which is 156k tokens.

One potential fix is to set self.batch_size == cfg.total_tokens // sae.cfg.context_size. But, then we are evaluating interpretability on inputs of different seq lens for different SAEs. Maybe this is fine? Or maybe we should just fix context_size to a single number for all SAEs?

If total tokens increased by 64x to 10M, this eval would become a bit more time consuming (from ~15 seconds to collect activations to 16 minutes on Gemma-2-2B on an RTX 3090).

I would randomly get this error on some runs:

```
Traceback (most recent call last):
  File "/workspace/SAE_Bench_Template/evals/autointerp/demo.py", line 67, in <module>
    results = run_eval(cfg, selected_saes_dict, str(device), api_key, save_logs_path=save_logs_path)
  File "/workspace/SAE_Bench_Template/evals/autointerp/main.py", line 487, in run_eval
    results = asyncio.run(autointerp.run())
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/workspace/SAE_Bench_Template/evals/autointerp/main.py", line 166, in run
    generation_examples, scoring_examples = self.gather_data()
  File "/workspace/SAE_Bench_Template/evals/autointerp/main.py", line 397, in gather_data
    iw_indices = get_iw_sample_indices(
  File "/workspace/SAE_Bench_Template/sae_bench_utils/indexing_utils.py", l
```

I think it's because after this, x = x[:, buffer:-buffer], x sums to 0. I think it may be because this line:

```
if torch.where(acts[..., i] < threshold, acts[..., i], 0.0).max() < 1e-6:
                continue
```

Includes the elements from buffer:-buffer that are removed in get_iw_sample_indices(). For the time being, I just wrapped get_iw_sample_indices() in a try except continue block.

GemmaScope SAEs were not trained on BOS tokens, do we know if BOS tokens are included in the SAE Lens activation store?

I've also attached a screenshot of topk, standard, and gemmascope on ctx len 128 inputs.
Screenshot 2024-10-19 at 5 59 03 PM

**Comment by callummcdougall** [comment]
See comments [here](https://mats-program.slack.com/archives/D07S936NNEB/p1729853644059319) - happy to crosspost them directly if it's more useful to centralize discussion on the GitHub thread.

**Comment by adamkarvonen** [comment]
I'll respond here in case anyone from Decode needs context.

> I'm not sure why the sae needed [sae.to](http://sae.to/)(device), but this might be because of a recently introduced bug in SAELens that I [fixed with a PR a few days ago](https://github.com/jbloomAus/SAELens/pull/347). So maybe not an issue any more? Lmk if it still is and I can further look into it

I've had to do this for over a month, I don't think this is newly introduced.

>  For the indexing error (point 4 in your PR comments), yep I think that should be the reason for it, since the sampling functions will deliberately exclude the buffer. Also to help with the dead latents problem I've now adjusted the code so that it uses the SAE's sparsity tensor (returned from SAE.from_pretrained) to filter out latents that have a frequency of below exp(-8) = 0.03%. I think SAELens sets dead feature frequencies as exp(-10) so could probably go a bit lower with this, but maybe it's low enough

This is a nice solution, but there's two potential issues with it. First, no SAE Bench SAEs have this sparsity tensor computed yet and `sparsity == None` (although it's probably not a big deal to compute it). Looking at `pretrained_saes.yaml`, many SAE Lens SAEs don't have it available. Second, at some point we are going to refactor evals so there's an inner `run_eval_single_sae()` function that takes any SAE object with an encode() and decode() function, so people using other SAEs can use the benchmark.  Neel is aware of at least 4 experimental new SAEs being developed, most of which are in standalone codebases, and it would be nice if they could easily benchmark them against our baselines. There's an example of what that would look like [here](https://github.com/adamkarvonen/SAE_Bench_Template/blob/f626447452d4e0e9bb9286959b73cbd8fa138e83/evals/sparse_probing/main.py#L193).

Requiring a sparsity tensor would add a bit of friction. An alternative could just be something like this at initialization:

```
sampled_latents = min(self.sae.cfg.d_sae, self.cfg.n_latents * 4)
self.latents = random.sample(range(self.sae.cfg.d_sae), k=sampled_latents)
```

And once sae activations are collected, just take the first self.cfg.n_latents non dead latents (although there isn't a guarantee that there will be this many alive latents, especially if self.cfg.n_latents is large). What do you think of this option? I'm not thrilled with it but it is pretty simple.

> I'm not super confident in how SAELens uses autocast and what dtypes should be used here, but I can check in with Joseph and the other SAELens folk and get back to you - or is the modification you made in autointerp_main_test.py working fine, in which case I can just apply that in my PR?

For the other evals I've just been doing [this](https://github.com/adamkarvonen/SAE_Bench_Template/blob/f626447452d4e0e9bb9286959b73cbd8fa138e83/evals/sparse_probing/main.py#L266-L287). @jbloomAus Any opinions here?

> The default behaviour for ActivationsStore is to match the SAE's config, both on context length and BOS token presence (it has context_size=sae.cfg.context_size and prepend_bos=sae.cfg.prepend_bos), so think that shouldn't be too much of a problem? Not sure what could be causing a lower value for the gemmascope models though.

If I look at a gemma-scope cfg, it has prepend bos as true. I think the desired behavior here is to have prepend bos as true, so Gemma receives inputs that begin with a bos token, and then filter the bos token activations out before encoding activations with the SAE. I do find it to be mildly annoying that Gemma-Scope SAEs weren't trained on even a few BOS tokens. Any thoughts @curt-tigges @jbloomAus ?

> Also for specifically the point about taking a while to gather activations for gemma, the results I found (i.e. what number of tokens resulted in good performance) was presumably with code that involved this error, so I think it's fine to bring the number down somewhat. 1m or 2m seems pretty reasonable (since my experiments on gpt2-small were under-collecting tokens by a factor of 1024/128=8). I've gone with 2m for this PR for now.

I'll note that 2m tokens of activations on a single layer is fairly small - around ~10 GB for Gemma-2-2B - where we optionally could precompute all activations for a layer, save them to disk, and then use the activations for all SAEs on that layer. But this isn't a big deal.

**Comment by callummcdougall** [comment]
> An alternative could just be something like this at initialization

Yeah it does seem a bit arbitrary what scale factor is chosen, since it depends on what the proportion of dead latents is. I've not looked at that many evals for different models, are you recommending the scale factor of 4 cause this seems like the value at which point we can basically guarantee we'll get alive latents? Or would something a bit lower like 2 work? I'm guessing we care less about models which have more than half their latents dead (also even if we don't have as many latents, this just increases variance of the score rather than introducing bias, since we take the mean over latents which were found to be alive).

An alternative would be to continually sample `self.cfg.n_latents` latents and keep the live ones, stopping when you have this many alive latents or you hit some max value e.g. 4. This would accomplish the same thing but slightly more flexibly. OTOH this is just annoying for topk SAEs because you're doing way more computation than necessary (every call of `encode_subset` requires you to compute all the activations). If this just isn't a big deal for the overall computational cost then maybe sticking with the easier scale factor of 4 method would work better.

> For the other evals I've just been doing [this](https://github.com/adamkarvonen/SAE_Bench_Template/blob/f626447452d4e0e9bb9286959b73cbd8fa138e83/evals/sparse_probing/main.py#L266-L287), which appeared to work for auto-interp as well

Cool, I've added that in now (including the `.to(device)` thing, if that won't get solved by the recent SAELens PR).

> If I look at a gemma-scope cfg, it has prepend bos as true. I think the desired behavior here is to have prepend bos as true, so Gemma receives inputs that begin with a bos token, and then filter the bos token activations out before encoding activations with the SAE

Ah okay I see. Happy to make this change (i.e. in line 324, could slice `sae_in` after it's defined, to remove the first token, iff the activation store had a BOS token), but I'll wait for confirmation on this.

> we optionally could precompute all activations for a layer, save them to disk, and then use the activations for all SAEs on that layer

Would that basically involve looking at the `selected_saes_dict` at the start, and grouping them according to which ones can re-use activations? Cause yeah I see the logic in this, but also it seems like the logical thing to do is have this kind of time saving go across evals not just across models in a single evals sweep (i.e. the `run_eval` function could also give you a bunch of pre-computed stuff, that way the caching doesn't have to be implemented differently for each eval). Guessing this might be hard though because every eval will have quite specific requirements and it's not necessarily the case that things can be reused like this?

**Comment by adamkarvonen** [comment]
> > An alternative could just be something like this at initialization
> 
> Yeah it does seem a bit arbitrary what scale factor is chosen, since it depends on what the proportion of dead latents is. I've not looked at that many evals for different models, are you recommending the scale factor of 4 cause this seems like the value at which point we can basically guarantee we'll get alive latents? Or would something a bit lower like 2 work? I'm guessing we care less about models which have more than half their latents dead (also even if we don't have as many latents, this just increases variance of the score rather than introducing bias, since we take the mean over latents which were found to be alive).
> 
> An alternative would be to continually sample `self.cfg.n_latents` latents and keep the live ones, stopping when you have this many alive latents or you hit some max value e.g. 4. This would accomplish the same thing but slightly more flexibly. OTOH this is just annoying for topk SAEs because you're doing way more computation than necessary (every call of `encode_subset` requires you to compute all the activations). If this just isn't a big deal for the overall computational cost then maybe sticking with the easier scale factor of 4 method would work better.

I like the method of just sampling `n_latents` until we have enough. My idea definitely felt very arbitrary. If the sampling is done on batches then it shouldn't be too bad for TopK? In this case we would probably also want to ensure that we break at some point if we haven't collected n_latents yet (which could easily be impossible if the SAE has many dead latents).

I took a look at number of dead latents in our SAEs by printing number of dead latents out of 500 over 200,000 tokens. The worst I saw in Gemma-Scope was 10% dead, the worst in our topk is 40%, and the worst in standard is 95%, which is pretty bad. I'm not sure how much effort should be put in to get enough alive latents in SAEs with < 50% alive latents.

> > If I look at a gemma-scope cfg, it has prepend bos as true. I think the desired behavior here is to have prepend bos as true, so Gemma receives inputs that begin with a bos token, and then filter the bos token activations out before encoding activations with the SAE
> 
> Ah okay I see. Happy to make this change (i.e. in line 324, could slice `sae_in` after it's defined, to remove the first token, iff the activation store had a BOS token), but I'll wait for confirmation on this.

@jbloomAus Looking at the tokens for Gemma-Scope, it looks like it's currently encoding BOS tokens, which Gemma-Scope wasn't trained on. We can't slice sae_in because num_bos_tokens is much larger than tokens.shape[0].

```
tokens = self.act_store.get_batch_tokens()
print(tokens.shape, (tokens == self.model.tokenizer.bos_token_id).sum())

torch.Size([1953, 1024]) tensor(3444, device='cuda:0')
```

However, it should be pretty simple to just create a mask that zeros out all bos, eos, and pad token activation locations.
Maybe something like this?

```
        all_acts = []
        for _tokens in tqdm(
            tokens.split(split_size=self.cfg.batch_size, dim=0),
            desc="Forward passes to get activation values",
        ):
            sae_in = self.act_store.get_activations(_tokens).squeeze(2).to(self.device)
            mask = (
                (_tokens == self.model.tokenizer.pad_token_id)
                | (_tokens == self.model.tokenizer.eos_token_id)
                | (_tokens == self.model.tokenizer.bos_token_id)
            ).to(device=self.device, dtype=sae_in.dtype)
            all_acts.append(
                encode_subset(self.sae, sae_in, latents=torch.tensor(self.latents))
                * (1 - mask[:, :, None])
            )

        acts = torch.cat(all_acts, dim=0)
```

I found that using all_acts.append() and a cat() at the end of the loop lowered peak memory usage and I could use up to 2x n_latents, which I find to be a bit surprising. The degree of how many more n_latents I could use varied from a 24GB GPU to a 48GB GPU, but the `all_acts` approach seemed to be consistently better.

> > we optionally could precompute all activations for a layer, save them to disk, and then use the activations for all SAEs on that layer
> 
> Would that basically involve looking at the `selected_saes_dict` at the start, and grouping them according to which ones can re-use activations? Cause yeah I see the logic in this, but also it seems like the logical thing to do is have this kind of time saving go across evals not just across models in a single evals sweep (i.e. the `run_eval` function could also give you a bunch of pre-computed stuff, that way the caching doesn't have to be implemented differently for each eval). Guessing this might be hard though because every eval will have quite specific requirements and it's not necessarily the case that things can be reused like this?

For the SHIFT and sparse probing evals, I just cached the activations at location `artifacts/sparse_probing/{model_name}/{hook_name}/{dataset_name}_activations.pt`. Then, before computing activations [I checked](https://github.com/adamkarvonen/SAE_Bench_Template/blob/main/evals/sparse_probing/main.py#L151) if they already exist.

I also added a flag to `run_eval()` for `cleanup_activations`, as activations use a lot of space. If True, [it deletes](https://github.com/adamkarvonen/SAE_Bench_Template/blob/main/evals/sparse_probing/main.py#L363) `artifacts/sparse_probing/` at the end of `run_eval()`, and then it's up to the user of the function to pass in a `selected_saes_dict` of SAEs on the same layer. Otherwise the user of the function can pass in arbitrary SAEs and delete the folder manually.

I'm not thrilled about introducing state by caching objects, but it's relatively simple and ensures that all SAEs from a given layer are evaluated on the same artifacts. Also, in the case of autointerp collecting activations on 2M tokens is reasonably quick and it's probably fine to skip this step if it's too much work or adds too much complexity.

**Comment by callummcdougall** [comment]
> If the sampling is done on batches then it shouldn't be too bad for `TopK`?

Don't know what you mean by not too bad. It would be strictly worse than just computing all latents at once, I think? Because the way the current hacky encode method works is that for topk architectures you have to compute all the latent activations in order to get any subset of them, so if you have to compute them all then there's no point computing them all more than once.

> the worst in our topk is 40%, and the worst in standard is 95%, which is pretty bad

If it does get this bad, then there are 2 logical solutions. One would be to just compute all the latents - idk how much of a big computational step up this is, obviously it's not going to be an order of magnitude step up because computing SAE activations isn't usually an order of magnitude more computationally difficult than doing a fwd pass on the model in the first place. The other would be to continually re-sample batches, but make sure they're being drawn without replacement so that we'll find enough features eventually. Doing this in a while loop is obvs gonna be worse in the worst case where we have to compute all features anyway, but presumably it'd be better in the case where we break out of the while loop faster. I don't know which of these options would be better because it depends on exactly how these evals plan to be used, in what environments / machines / contexts etc. But I'm happy to implement one of these options, whichever you think makes most sense.

> For the SHIFT and sparse probing evals, I just cached the activations at location artifacts/sparse_probing/{model_name}/{hook_name}/{dataset_name}_activations.pt. Then, before computing activations [I checked](https://github.com/adamkarvonen/SAE_Bench_Template/blob/main/evals/sparse_probing/main.py#L151) if they already exist.

I'm happy to implement that. But I'll mention again that it seems like an extreme waste, because this kind of data should be shared between evals - unless I'm missing something?

**Pull request merged**
