### PR TITLE
Rename utils to avoid name conflict

### PR DESCRIPTION
**Pull request by koayon**

### CODE REVIEW

**Comment by canrager** [comment]
thanks! Is the main intent of this PR to rename the `utils` folder to `sae_bench_utils`? If yes, would you be able to make a PR with only import lines and filenames changed?

I'm not sure if there's some other fuctionality contained in this PR. Could you please use `nbstripout --install` to make sure you're not pushing the cell outputs in notebooks?

**Comment by koayon** [comment]
Hey! Yes that's the only functional change. 

The other changes that have been made are purely cosmetic - the imports have been ordered by isort and the formatter has made some readability changes.

Ahhh, nbstripout looks super useful! Agree it's good to not push the Jupyter cell changes, I'll revert the notebook parts to only change the import name part - thanks for the rec 🙏

**Comment by koayon** [comment]
I don't think I saw any formatter in the repo but if you have an opinionated formatter that you like then I would be happy to use those settings instead 👌

**Review by canrager — APPROVED** [review]

**Comment by canrager** [comment]
Thanks! I'm sorry, I'm not aware of a clean way to automatically apply NB stripout, Claude's suggestions seem like some overhead. Are you aware of best practices?

**Pull request merged**
