### PR TITLE
Feature Absorption Eval

### PR DESCRIPTION
**Pull request by chanind**
This PR adds a feature absorption eval. This likely needs to be more battle-tested by @jbloomaus, but hopefully it's in a decent enough shape to at least run. I didn't use the existing k-sparse probing code in the end since it seemed harder to integrate with our code than I thought initially - that can be done at a later stage.

I removed the feature attribution check from this version of the feature absorption code since we can't run attribution on later SAE layers. I replaced it instead with a check that the absorbing feature must contribute at least 40% of the probe direction into the activation (this likely needs to be further tuned).

### CODE REVIEW

**Comment by canrager** [comment]
(fixed conflicts after merging Kola's PR that renamed `utils` --> `sae_bench_utils`)

**Comment by adamkarvonen** [comment]
Thanks! One other ask is to provide an example input / output pair (it's fine if you only run a single SAE, although you may want to graph multiple SAEs) and check that you can successfully plot the output json file using `graphing.ipynb`.

This is how I did my input / output pair: This [test](https://github.com/adamkarvonen/SAE_Bench_Template/blob/main/tests/test_shift_and_tpp.py) will run the eval on a single SAE for a given set of hyperparameters and check that the results match these [results](https://github.com/adamkarvonen/SAE_Bench_Template/tree/main/tests/test_data) within a tolerance.


In graphing.ipynb, I set:

```
results = ""
filename = "tests/test_data/pythia-70m-deduped_scr_layer_4_expected_eval_results.json"
k = 2
custom_metric = f'scr_dir1_threshold_{k}'
```

And clicked run all to verify that a plot was successfully created. I know you're pretty busy with Neel's training phase. If you're too busy to get to this soon, Can can do it, or I can do it once I'm back from COLM.

**Comment by chanind** [comment]
Got it, I'll try to get on this later this week!

**Comment by chanind** [comment]
I ran this in a jupyter notebook, let me know if this what what's supposed to happen! Notebook is here: https://colab.research.google.com/drive/125dvmB6gGJ4av7GSxlAwg8BLRz1uL-dO?usp=sharing

[absorption_results_dict.json](https://github.com/user-attachments/files/17347854/absorption_results_dict.json)

absorption_rate

**Pull request merged**
